version: "3.9"

services:
  chat_saver:
    build: .
    container_name: chat_saver_app
    restart: unless-stopped
    volumes:
      # ذخیره دائمی فایل‌های دیتابیس و آپلودها
      - ./chats:/app/chats
      - ./static/uploads:/app/static/uploads
    ports:
      - "8000:8000"  # پورت برنامه FastAPI
    environment:
      - PYTHONUNBUFFERED=1  # برای نمایش لاگ‌ها به صورت real-time
    networks:
      - chat_network

networks:
  chat_network:
    name: chat_network
    driver: bridge